nginx:
  container_name: nginx
  image: nginx
  ports:
  - 80:80/tcp
  - 443:443/tcp
  - 8080:8080/tcp
  volumes:
  - ${PWD}/opt/acme:/var/www/letsencrypt
  - ${PWD}/opt/certs:/etc/nginx/certs
  - ${PWD}/opt/nginx:/etc/nginx/conf.d
  - ${PWD}/opt/vhost:/etc/nginx/vhost.d
  restart: 'always'
  stdin_open: true
  tty: true
mysql:
  image: mariadb
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: yes
  restart: 'always'
  stdin_open: true
  tty: true
cache:
  image: memcached
  restart: 'always'
  stdin_open: true
  tty: true
redis:
  image: redis
  restart: 'always'
  stdin_open: true
  tty: true
discovery:
  image: jwilder/docker-gen
  command: -config /etc/discovery.conf
  links:
  - nginx:nginx
  - mysql:mysql
  - cache:cache
  - redis:redis
  volumes_from:
  - nginx
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock:ro
  - ${PWD}/etc/discovery.conf:/etc/discovery.conf
  - ${PWD}/etc/nginx/proxy:/etc/docker-gen/templates
  restart: 'always'
  stdin_open: true
  tty: true
submarine:
  build: .
  env_file: .env
  command: --test-cert --webroot
  volumes:
  - ${PWD}/opt/www/${WP_DOMAIN}:/submarine
  - ${PWD}/opt/acme:/submarine/acme
  - ${PWD}/opt/certs:/submarine/ssl
  links:
  - nginx:nginx
  - mysql:mysql
  - cache:cache
  - redis:redis
  restart: always
  stdin_open: true
  tty: true
